'use client';

import { useState } from 'react';

// These are real, publicly accessible reports and announcements—not invented case studies.
const reports = [
  { region: 'EUROPEAN UNION · 2025', source: 'EU Publications Office', title: 'AI for border management and customs controls', copy: 'A review of 75 EU-funded projects shows how AI is being applied to sensing, threat detection, biometrics, and real-time border decisions.', href: 'https://op.europa.eu/en/publication-detail/-/publication/54ab1d78-c4f4-11f0-8da2-01aa75ed71a1/language-en', image: 'https://images.unsplash.com/photo-1517148815978-75f6acaaf32c?auto=format&fit=crop&w=900&q=80' },
  { region: 'EUROPE · SEP 2025', source: 'European Commission', title: 'European innovation strengthens border management', copy: 'A Turku demonstration brought together AI platforms, data fusion, digital twins, and next-generation sensors for border surveillance.', href: 'https://home-affairs.ec.europa.eu/news/european-innovation-strengthens-border-management-new-eu-technology-2025-09-04_en', image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=900&q=80' },
  { region: 'UNITED KINGDOM · 2025', source: 'GOV.UK', title: 'Police use of facial recognition: factsheet', copy: 'The official guide explains live and retrospective facial recognition, including operator review, watchlists, public notice, and deletion safeguards.', href: 'https://www.gov.uk/government/publications/police-use-of-facial-recognition/police-use-of-facial-recognition-factsheet', image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=900&q=80' },
  { region: 'GLOBAL · 2024 EVALUATION', source: 'NIST', title: 'Face in Video Evaluation (FIVE)', copy: 'NIST evaluates whether face-recognition algorithms can identify—or correctly ignore—people appearing in degraded real-world video sequences.', href: 'https://www.nist.gov/programs-projects/face-video-evaluation-five', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80' },
  { region: 'EUROPE · 2026 PROJECT REPORT', source: 'CORDIS / European Commission', title: 'EURMARS: multi-authority border security', copy: 'The project combines ground, UAV, satellite, AI detection, tracking, behaviour analysis, and a shared command-and-control environment.', href: 'https://cordis.europa.eu/project/id/101073985/reporting/es', image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80' },
  { region: 'EUROPE · HORIZON PROJECT', source: 'CORDIS / European Commission', title: 'PopEye: privacy-preserving border biometrics', copy: 'A research project explores on-the-move biometric verification while explicitly addressing GDPR, AI Act compliance, bias, and data protection.', href: 'https://cordis.europa.eu/project/id/101168317', image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80' }
];

export function NewsCarousel() {
  const [start, setStart] = useState(0);
  const visible = reports.slice(start, start + 3);
  const next = () => setStart((value) => (value + 1) % reports.length);
  const previous = () => setStart((value) => (value - 1 + reports.length) % reports.length);
  return <section className="field-reports section"><div className="reports-heading"><div><p className="eyebrow">Field reports · verified sources</p><h2>What the world is learning about intelligent borders.</h2><p>Research, policy, and deployments that make the case for a more proactive operational picture.</p></div><div className="carousel-controls"><button type="button" onClick={previous} aria-label="Previous reports">←</button><span>{String(start + 1).padStart(2, '0')} — {String(Math.min(start + 3, reports.length)).padStart(2, '0')}</span><button type="button" onClick={next} aria-label="Next reports">→</button></div></div><div className="reports-track">{visible.map((report) => <article className="report-card" key={report.title}><img src={report.image} alt=""/><div className="report-body"><div className="report-meta"><span>{report.region}</span><b>{report.source}</b></div><h3>{report.title}</h3><p>{report.copy}</p><a href={report.href} target="_blank" rel="noreferrer">Read the report <b>↗</b></a></div></article>)}</div><div className="carousel-dots">{reports.map((report, index) => <button type="button" key={report.title} className={index === start ? 'active' : ''} onClick={() => setStart(index)} aria-label={`Show report ${index + 1}`} />)}</div><p className="reports-note">Sources open in a new tab. SentryX shares these references for context; reported results do not represent SentryX performance claims.</p></section>;
}
