import { Reveal } from './Reveal';

// The editorial block keeps the original card DOM/classes so its visual treatment is unchanged.
const reports = [
  ['FIELD NOTE', 'WEST BENGAL • NOV 2024', '₹6.9 Crore Yaba Drug Bust at Ghojadanga', 'BSF forces intercepted a massive cache of 70,000 Yaba tablets hidden near a border outpost parking lot. Passive CCTV failed to raise alarms automatically, proving the critical need for AI-driven suspicious activity detection and object tracking.', 'Read the report - The Hindu', 'https://www.thehindu.com/news/national/west-bengal/bsf-seizes-narcotics-worth-over-6-crores-near-bangladesh-border-in-west-bengal/article68910810.ece', 'sentryx-article-1'],
  ['OPERATIONS', 'NADIA, WB • SEPT 2026', 'Smugglers exploit darkness to bypass fences', 'Smugglers successfully threw a ₹17.4 crore gold and contraband consignment over the India-Bangladesh barbed-wire fencing under the cover of darkness. This highlights a severe vulnerability that AI-powered virtual fencing and night-time movement detection can solve instantly.', 'Read the report - The Statesman', 'https://www.thestatesman.com/cities/kolkata/bsf-seizes-89-gold-biscuits-worth-rs-17-40-crore-on-bengal-bangladesh-border-1503635296.html', 'sentryx-article-2'],
  ['TECHNOLOGY', 'ASSAM • AUG 2021', 'The threat of porous riverine frontiers', 'With highly porous riverine borders frequently used for cross-border infiltration and narcotics trafficking, conventional human patrolling is insufficient. Intelligent human and vehicle classification algorithms are essential to provide 24/7 continuous threat logging.', 'Read the report - ANI News', 'https://www.aninews.in/news/national/general-news/bsf-apprehends-drug-trafficker-with-3700-yaba-tablets-from-india-bangladesh-border20210810151356/', 'sentryx-article-3']
];

export function UrgentReports() {
  return <><section className="page-hero section"><p className="eyebrow">Real-world border incidents</p><h1>The urgent need for <i>intelligent borders</i></h1><p className="lead">Real incidents of smuggling, trafficking, and infiltration demonstrating why passive CCTV is no longer enough.</p></section><Reveal className="section editorial-grid">{reports.map(([type, tag, title, copy, linkText, href], i) => <article className="article-card" key={title}><img src={`https://images.unsplash.com/photo-${i === 0 ? '1557597774-9d273605dfa9' : i === 1 ? '1517148815978-75f6acaaf32c' : '1541888946425-d0fbb186c5f6'}?auto=format&fit=crop&w=900&q=82`} alt="Border surveillance camera infrastructure" /><div><p className="eyebrow">{type} · {tag}</p><h2>{title}</h2><p>{copy}</p><a className="text-link" href={href} target="_blank" rel="noreferrer">{linkText} <b>↗</b></a></div></article>)}</Reveal></>;
}
