'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

const API_BASE = process.env.NEXT_PUBLIC_IBVAP_API_BASE_URL || 'https://students-problems-signing-pencil.trycloudflare.com';
const NATIVE_VIDEO = { width: 1920, height: 1080 };
const INITIAL_FENCE = [{ x: 104, y: 142 }, { x: 306, y: 142 }, { x: 268, y: 394 }, { x: 80, y: 394 }];
const INITIAL_TRIPWIRE = [{ x: 252, y: 302 }, { x: 650, y: 310 }];

function decodeAlerts(value) {
  if (!value) return [];
  try { return JSON.parse(atob(value)); } catch { return []; }
}

export function Workbench() {
  const canvasRef = useRef(null);
  const [file, setFile] = useState(null); const [youtubeUrl, setYoutubeUrl] = useState('');
  const [tool, setTool] = useState('fence'); const [fence, setFence] = useState(null); const [tripwire, setTripwire] = useState(null);
  const [dragging, setDragging] = useState(null); const [maxDuration, setMaxDuration] = useState(120); const [nightMode, setNightMode] = useState(false); const [enableAnpr, setEnableAnpr] = useState(true);
  const [status, setStatus] = useState('Ready for an input source.'); const [processing, setProcessing] = useState(false); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const background = useMemo(() => 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f6?auto=format&fit=crop&w=1280&q=82', []);

  // Canvas is display-sized, while exported coordinates are always scaled to the camera's native 1920×1080.
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); const img = new Image(); img.crossOrigin = 'anonymous'; img.src = background;
    const drawHandle = (pt, color, label) => { ctx.beginPath(); ctx.arc(pt.x, pt.y, 7, 0, Math.PI * 2); ctx.fillStyle = color; ctx.fill(); ctx.strokeStyle = '#fff'; ctx.lineWidth = 2; ctx.stroke(); if (label) { ctx.fillStyle = '#17242d'; ctx.font = '600 10px Inter'; ctx.fillText(label, pt.x + 10, pt.y - 8); } };
    const draw = () => { ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.drawImage(img, 0, 0, canvas.width, canvas.height); ctx.fillStyle = 'rgba(12, 25, 33, .18)'; ctx.fillRect(0, 0, canvas.width, canvas.height);
      if (fence?.length >= 3) { ctx.beginPath(); ctx.moveTo(fence[0].x, fence[0].y); fence.slice(1).forEach(p => ctx.lineTo(p.x, p.y)); ctx.closePath(); ctx.fillStyle = 'rgba(225,149,171,.28)'; ctx.fill(); ctx.strokeStyle = '#e195ab'; ctx.lineWidth = 2; ctx.stroke(); fence.forEach((p, i) => drawHandle(p, '#e195ab', String(i + 1))); }
      if (tripwire?.length === 2) { const [a, b] = tripwire; ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.strokeStyle = '#ffe38d'; ctx.lineWidth = 3; ctx.stroke(); const mx = (a.x + b.x) / 2; const my = (a.y + b.y) / 2; ctx.beginPath(); ctx.moveTo(mx, my); ctx.lineTo(mx, my - 25); ctx.strokeStyle = '#ffe38d'; ctx.stroke(); drawHandle(a, '#ffe38d', 'A'); drawHandle(b, '#ffe38d', 'B'); }
    }; img.onload = draw; draw(); return () => { img.onload = null; };
  }, [background, fence, tripwire]);

  function pointerPosition(event) { const rect = canvasRef.current.getBoundingClientRect(); return { x: Math.max(0, Math.min(800, event.clientX - rect.left)), y: Math.max(0, Math.min(450, event.clientY - rect.top)) }; }
  function startDrag(event) { const p = pointerPosition(event); const shapes = [{ name: 'fence', points: fence }, { name: 'tripwire', points: tripwire }]; for (const shape of shapes) { const index = shape.points?.findIndex(pt => Math.hypot(pt.x - p.x, pt.y - p.y) < 16); if (index >= 0) { setDragging({ shape: shape.name, index }); return; } } }
  function drag(event) { if (!dragging) return; const p = pointerPosition(event); const setter = dragging.shape === 'fence' ? setFence : setTripwire; setter(points => points?.map((point, i) => i === dragging.index ? p : point)); }
  function exportPayload() { const sx = NATIVE_VIDEO.width / 800; const sy = NATIVE_VIDEO.height / 450; const payload = {}; if (fence) payload.fence_polygon = JSON.stringify(fence.map(p => [Math.round(p.x * sx), Math.round(p.y * sy)])); if (tripwire) payload.tripwire_line = JSON.stringify(tripwire.map(p => [Math.round(p.x * sx), Math.round(p.y * sy)])); return payload; }
  function downloadReport() { if (!result?.alerts?.length) return; const blob = new Blob([JSON.stringify(result.alerts, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'incident_report.json'; a.click(); URL.revokeObjectURL(url); }
  async function runAnalytics(event) { event.preventDefault(); setError(''); setResult(null); if (!file && !youtubeUrl.trim()) { setError('Add an MP4/AVI/MOV file or a public YouTube URL first.'); return; } const form = new FormData(); if (file) form.append('video_file', file); else form.append('youtube_url', youtubeUrl.trim()); const zones = exportPayload(); Object.entries(zones).forEach(([key, value]) => form.append(key, value)); form.append('enable_anpr', String(enableAnpr)); form.append('night_mode', String(nightMode)); form.append('max_duration', String(maxDuration)); setProcessing(true); setStatus('Uploading source and preparing edge inference…'); try { const response = await fetch(`${API_BASE}/api/v1/analytics/full`, { method: 'POST', body: form }); if (!response.ok) throw new Error(`Inference returned ${response.status}`); setStatus('ByteTrack Engine associating tracks…'); const blob = await response.blob(); const plates = JSON.parse(response.headers.get('X-IBVAP-Plates-Detected') || '{}'); const alerts = decodeAlerts(response.headers.get('X-IBVAP-Alerts-JSON')); setResult({ videoUrl: URL.createObjectURL(blob), breaches: response.headers.get('X-IBVAP-Breach-Count') || '0', plates, alerts }); setStatus('Analysis complete. Evidence is ready to review.'); } catch (e) { setError(e.message || 'The analytics service could not be reached.'); setStatus('Analysis paused.'); } finally { setProcessing(false); } }
  return <section className="workbench section"><div className="section-heading inline"><div><p className="eyebrow">Tactical workspace</p><h2>Shape the perimeter. Read the signal.</h2></div><span className="workbench-status"><i className={processing ? 'pulse' : ''} /> {status}</span></div>
    <form className="workbench-grid" onSubmit={runAnalytics}><div className="calibrator panel"><div className="panel-head"><div><p className="eyebrow">01 · Zone calibration</p><h3>Set your rules of engagement</h3></div><button type="button" className="clear-btn" onClick={() => { setFence(null); setTripwire(null); }}>Clear zones</button></div><div className="tool-row"><button type="button" className={tool === 'fence' ? 'tool active' : 'tool'} onClick={() => setTool('fence')}>◈ Restricted zone</button><button type="button" className={tool === 'tripwire' ? 'tool active' : 'tool'} onClick={() => setTool('tripwire')}>⌁ Tripwire</button><button type="button" className="tool preset" onClick={() => tool === 'fence' ? setFence(INITIAL_FENCE) : setTripwire(INITIAL_TRIPWIRE)}>+ Add {tool === 'fence' ? 'zone' : 'line'}</button></div><div className="calibration-frame"><canvas ref={canvasRef} width="800" height="450" onPointerDown={startDrag} onPointerMove={drag} onPointerUp={() => setDragging(null)} onPointerLeave={() => setDragging(null)} /><span className="frame-label">CALIBRATION FRAME · 1920 × 1080 NATIVE</span></div><div className="zone-readout">{(fence || tripwire) ? <><span>Payload preview</span><code>{JSON.stringify(exportPayload())}</code></> : <span>Select a tool and add a preset to begin shaping a zone.</span>}</div></div>
      <div className="analysis panel"><p className="eyebrow">02 · Video processing</p><h3>Run intelligent analytics</h3><label className="source-drop">{file ? <><b>{file.name}</b><small>{(file.size / 1024 / 1024).toFixed(1)} MB · ready to process</small></> : <><b>Drop a surveillance clip</b><small>MP4, AVI or MOV · up to 500 MB</small></>}<input type="file" accept="video/mp4,video/quicktime,video/x-msvideo" onChange={e => setFile(e.target.files?.[0] || null)} /></label><div className="or-divider"><span>or use a public YouTube URL</span></div><input className="text-input" value={youtubeUrl} onChange={e => setYoutubeUrl(e.target.value)} placeholder="https://youtube.com/watch?v=…" /><label className="range-label"><span>Max analysis duration</span><output>{maxDuration}s</output><input type="range" min="10" max="480" step="10" value={maxDuration} onChange={e => setMaxDuration(Number(e.target.value))} /></label><div className="switches"><label><input type="checkbox" checked={enableAnpr} onChange={e => setEnableAnpr(e.target.checked)} /><span />ANPR recognition</label><label><input type="checkbox" checked={nightMode} onChange={e => setNightMode(e.target.checked)} /><span />Night mode</label></div>{error && <p className="error-message">{error}</p>}<button className="button dark run-button" disabled={processing}>{processing ? 'Processing perimeter…' : 'Run intelligent analytics'} <b>{processing ? '◌' : '↗'}</b></button></div>
    </form>{result && <div className="results panel"><div className="results-head"><div><p className="eyebrow">03 · Defense results</p><h3>Annotated surveillance feed</h3></div><div className="result-actions"><span className="breach-count">{result.breaches} <small>breaches detected</small></span><button type="button" className="button outline" onClick={downloadReport}>Download audit JSON ↧</button></div></div><video className="result-video" controls src={result.videoUrl} /><div className="result-grid"><div><p className="eyebrow">Detected plates</p>{Object.keys(result.plates).length ? Object.entries(result.plates).map(([id, plate]) => <div className="plate-row" key={id}><span>Track #{id}</span><b>{plate}</b></div>) : <p className="muted">No plates surfaced in this clip.</p>}</div><div><p className="eyebrow">Incident timeline</p>{result.alerts.length ? result.alerts.slice(0, 5).map((alert, i) => <div className="alert-row" key={i}><i />{alert.message || alert.type || 'Perimeter event'}<small>{alert.timestamp || 'just now'}</small></div>) : <p className="muted">No incidents reported.</p>}</div></div></div>}
  </section>;
}
